logging:
  path: logs/
  level:
    org:
      springframework:
        data: DEBUG

  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
    
eureka: 
  client: 
      register-with-eureka: false
      fetch-registry: false 
---
# Dev profile
spring:
  profiles: dev
  application:
    name: springcloud2webflux
  jpa:
    show-sql: true
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/d_auth?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  redis:
    host: 127.0.0.1
    port: 6379
#    database: 0
    pool:
      max-idle: 2
      min-idle: 1
      max-active: 5
      max-wait: -1

server:
  port: 2222